// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 The meta-amiga authors
//
// GENERATED by scripts/gen_slot_tables.py from docs/reference/dma-slot-allocation.yaml.
// Do not edit: change the YAML and regenerate. Transcribed from the Amiga Hardware
// Reference Manual, 3rd edition, and NOT verified against hardware.
// yaml-sha256: ad3fbf41ab1ad0291912317135ab48fa0b0a5a67cd635468d74f6bced2630616

#ifndef META_AMIGA_CORE_CHIPSET_SLOT_TABLES_HPP
#define META_AMIGA_CORE_CHIPSET_SLOT_TABLES_HPP

#include <array>
#include <cstdint>

namespace meta::amiga::core::chipset::tables {

using SpriteSlots = std::array<std::uint8_t, 2>;

inline constexpr std::array<std::uint8_t, 3> kRefreshSlots{0x01, 0x03, 0x05};
// The manual counts 4 refresh slots; 1 has no determined index and is not placed.
inline constexpr int kRefreshSlotsUnplaced = 1;
inline constexpr std::array<std::uint8_t, 3> kDiskSlots{0x07, 0x09, 0x0B};
inline constexpr std::array<std::uint8_t, 4> kAudioSlots{0x0D, 0x0F, 0x11, 0x13};
inline constexpr std::array<SpriteSlots, 8> kSpriteSlots{
    SpriteSlots{0x15, 0x17},
    SpriteSlots{0x19, 0x1B},
    SpriteSlots{0x1D, 0x1F},
    SpriteSlots{0x21, 0x23},
    SpriteSlots{0x25, 0x27},
    SpriteSlots{0x29, 0x2B},
    SpriteSlots{0x2D, 0x2F},
    SpriteSlots{0x31, 0x33}};

// Plane number per offset within the fetch group; 0 is an offset no plane claims.
inline constexpr int kLoresGroupClocks = 8;
inline constexpr int kLoresMaxPlanes = 6;
inline constexpr std::array<std::uint8_t, 8> kLoresPlaneByOffset{0, 4, 6, 2, 0, 3, 5, 1};
inline constexpr int kHiresGroupClocks = 4;
inline constexpr int kHiresMaxPlanes = 4;
inline constexpr std::array<std::uint8_t, 4> kHiresPlaneByOffset{4, 2, 3, 1};
// AGA fetch modes: no table. The source marks them UNVERIFIED (no permitted source
// held), so the allocator is OCS/ECS only until one is transcribed.

inline constexpr int kLoresDdfstrtNormal = 0x38;
inline constexpr int kLoresDdfstopNormal = 0xD0;
inline constexpr int kLoresWordsNormal = 20;
inline constexpr int kHiresDdfstrtNormal = 0x3C;
inline constexpr int kHiresDdfstopNormal = 0xD4;
inline constexpr int kHiresWordsNormal = 40;

inline constexpr int kEarliestFetch = 0x18;
inline constexpr int kHardwareFetchStop = 0xD8;
inline constexpr bool kOutOfRangeDdfVerified = false;

inline constexpr int kCpuOwnsParity = 0;
inline constexpr bool kHardwareVerified = false;

}  // namespace meta::amiga::core::chipset::tables

#endif  // META_AMIGA_CORE_CHIPSET_SLOT_TABLES_HPP
