#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 The meta-amiga authors
#
# Generates the DMA slot tables the core compiles against from
# docs/reference/dma-slot-allocation.yaml, so the numbers have exactly one source. The
# outputs are checked in, so building needs no Python; `--check` fails when they have
# drifted from the YAML, and CTest runs it.
#
# The generator refuses data that breaks an invariant the transcription itself states,
# rather than emitting a table the allocator would then silently trust:
#   - every fixed allocation is on the parity the 68000 does NOT own (S1, S4);
#   - a bitplane pattern names each plane 1..max_planes exactly once;
#   - an UNVERIFIED (null) entry stays absent, never becomes a number.

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
YAML_PATH = ROOT / "docs/reference/dma-slot-allocation.yaml"
CORE_HEADER = ROOT / "src/core/include/meta_amiga/core/chipset/slot_tables.hpp"
TEST_HEADER = ROOT / "tests/unit/slot_table_expectations.hpp"

SKIP = 77  # CTest SKIP_RETURN_CODE


class TableError(ValueError):
    pass


def load_yaml(text: str) -> dict:
    import yaml  # imported late so a missing PyYAML is a skip, not a crash

    return yaml.safe_load(text)


def _hex(v: int) -> str:
    return f"0x{v:02X}"


def _banner(digest: str) -> str:
    return (
        "// SPDX-License-Identifier: GPL-3.0-or-later\n"
        "// Copyright (C) 2026 The meta-amiga authors\n"
        "//\n"
        "// GENERATED by scripts/gen_slot_tables.py from docs/reference/dma-slot-allocation.yaml.\n"
        "// Do not edit: change the YAML and regenerate. Transcribed from the Amiga Hardware\n"
        "// Reference Manual, 3rd edition, and NOT verified against hardware.\n"
        f"// yaml-sha256: {digest}\n"
    )


def _validate(data: dict) -> None:
    cpu_parity = data["line"]["cpu_owns_parity"]
    if cpu_parity not in ("even", "odd"):
        raise TableError(f"line.cpu_owns_parity must be even or odd, not {cpu_parity!r}")
    cpu_bit = 0 if cpu_parity == "even" else 1

    fixed = data["fixed_allocations"]
    slots: list[tuple[str, int]] = []
    slots += [("refresh", s) for s in fixed["refresh"]["slots"]]
    slots += [("disk", s) for s in fixed["disk"]["slots"]]
    slots += [(f"audio {c}", s) for c, s in fixed["audio"]["slots_by_channel"].items()]
    for n, pair in fixed["sprite"]["slots_by_sprite"].items():
        slots += [(f"sprite {n}", s) for s in pair]
    seen: dict[int, str] = {}
    for who, s in slots:
        if s % 2 == cpu_bit:
            raise TableError(f"{who} slot {_hex(s)} is on the 68000's {cpu_parity} clock")
        if s in seen:
            raise TableError(f"{who} and {seen[s]} both claim slot {_hex(s)}")
        seen[s] = who

    for mode in ("lores", "hires"):
        m = data["bitplane_fetch"][mode]
        pattern = m["plane_by_offset"]
        if len(pattern) != m["group_clocks"]:
            raise TableError(f"{mode} pattern has {len(pattern)} offsets, group is {m['group_clocks']}")
        planes = sorted(p for p in pattern if p is not None)
        if planes != list(range(1, m["max_planes"] + 1)):
            raise TableError(f"{mode} pattern must name planes 1..{m['max_planes']} once each")


def render_core(data: dict, digest: str) -> str:
    _validate(data)
    fixed = data["fixed_allocations"]
    bpl = data["bitplane_fetch"]
    win = data["fetch_window"]
    lim = data["limits"]

    def pattern(mode: str) -> str:
        return ", ".join("0" if p is None else str(p) for p in bpl[mode]["plane_by_offset"])

    refresh = ", ".join(_hex(s) for s in fixed["refresh"]["slots"])
    disk = ", ".join(_hex(s) for s in fixed["disk"]["slots"])
    audio = ", ".join(_hex(fixed["audio"]["slots_by_channel"][c]) for c in range(4))
    sprites = ",\n    ".join(
        "SpriteSlots{" + ", ".join(_hex(s) for s in fixed["sprite"]["slots_by_sprite"][n]) + "}"
        for n in range(8)
    )
    aga_note = (
        "// AGA fetch modes: no table. The source marks them UNVERIFIED (no permitted source\n"
        "// held), so the allocator is OCS/ECS only until one is transcribed.\n"
        if bpl["aga"]["plane_by_offset"] is None
        else ""
    )
    return (
        _banner(digest)
        + """
#ifndef META_AMIGA_CORE_CHIPSET_SLOT_TABLES_HPP
#define META_AMIGA_CORE_CHIPSET_SLOT_TABLES_HPP

#include <array>
#include <cstdint>

namespace meta::amiga::core::chipset::tables {

using SpriteSlots = std::array<std::uint8_t, 2>;

"""
        + f"""inline constexpr std::array<std::uint8_t, {len(fixed["refresh"]["slots"])}> kRefreshSlots{{{refresh}}};
// The manual counts {fixed["refresh"]["count"]} refresh slots; {fixed["refresh"]["unverified_slots"]} has no determined index and is not placed.
inline constexpr int kRefreshSlotsUnplaced = {fixed["refresh"]["unverified_slots"]};
inline constexpr std::array<std::uint8_t, {len(fixed["disk"]["slots"])}> kDiskSlots{{{disk}}};
inline constexpr std::array<std::uint8_t, 4> kAudioSlots{{{audio}}};
inline constexpr std::array<SpriteSlots, 8> kSpriteSlots{{
    {sprites}}};

// Plane number per offset within the fetch group; 0 is an offset no plane claims.
inline constexpr int kLoresGroupClocks = {bpl["lores"]["group_clocks"]};
inline constexpr int kLoresMaxPlanes = {bpl["lores"]["max_planes"]};
inline constexpr std::array<std::uint8_t, {bpl["lores"]["group_clocks"]}> kLoresPlaneByOffset{{{pattern("lores")}}};
inline constexpr int kHiresGroupClocks = {bpl["hires"]["group_clocks"]};
inline constexpr int kHiresMaxPlanes = {bpl["hires"]["max_planes"]};
inline constexpr std::array<std::uint8_t, {bpl["hires"]["group_clocks"]}> kHiresPlaneByOffset{{{pattern("hires")}}};
{aga_note}
inline constexpr int kLoresDdfstrtNormal = {_hex(win["lores"]["ddfstrt_normal"])};
inline constexpr int kLoresDdfstopNormal = {_hex(win["lores"]["ddfstop_normal"])};
inline constexpr int kLoresWordsNormal = {win["lores"]["words_normal"]};
inline constexpr int kHiresDdfstrtNormal = {_hex(win["hires"]["ddfstrt_normal"])};
inline constexpr int kHiresDdfstopNormal = {_hex(win["hires"]["ddfstop_normal"])};
inline constexpr int kHiresWordsNormal = {win["hires"]["words_normal"]};

inline constexpr int kEarliestFetch = {_hex(lim["earliest_fetch"])};
inline constexpr int kHardwareFetchStop = {_hex(lim["hardware_fetch_stop"])};
inline constexpr bool kOutOfRangeDdfVerified = {"false" if lim["out_of_range_behaviour"] is None else "true"};

inline constexpr int kCpuOwnsParity = {0 if data["line"]["cpu_owns_parity"] == "even" else 1};
inline constexpr bool kHardwareVerified = {"true" if data["meta"]["hardware_verified"] else "false"};

}}  // namespace meta::amiga::core::chipset::tables

#endif  // META_AMIGA_CORE_CHIPSET_SLOT_TABLES_HPP
"""
    )


def render_expectations(data: dict, digest: str) -> str:
    p = data["predicted_cpu_slots_pal"]

    def rows(table: dict) -> str:
        out = [f"    PredictedRow{{Mode::Off, 0, {table['bitplane_dma_off']}}},"]
        for mode in ("lores", "hires"):
            for planes, value in sorted(table[mode].items()):
                out.append(f"    PredictedRow{{Mode::{mode.capitalize()}, {planes}, {value}}},")
        return "\n".join(out)

    n_even = 1 + len(p["even_left_to_cpu"]["lores"]) + len(p["even_left_to_cpu"]["hires"])
    n_odd = 1 + len(p["odd_free_all_dma_enabled"]["lores"]) + len(p["odd_free_all_dma_enabled"]["hires"])
    return (
        _banner(digest)
        + f"""//
// The PREDICTED column of the per-line CPU-slot table (reference section 7). It was worked
// out by hand from the manual, independently of the allocator, so asserting the allocator
// reproduces it checks the mechanism against the paper. No measured column exists.

#ifndef META_AMIGA_TESTS_SLOT_TABLE_EXPECTATIONS_HPP
#define META_AMIGA_TESTS_SLOT_TABLE_EXPECTATIONS_HPP

#include <array>

namespace meta::amiga::test::slot_tables {{

enum class Mode {{ Off, Lores, Hires }};

struct PredictedRow {{
    Mode mode;
    int planes;
    int value;
}};

inline constexpr int kPalClocks = {p["even_clocks_total"] + p["odd_clocks_total"]};
inline constexpr int kEvenClocksTotal = {p["even_clocks_total"]};
inline constexpr int kOddClocksTotal = {p["odd_clocks_total"]};
inline constexpr int kFixedOddSlots = {p["fixed_odd_slots"]};
inline constexpr int kUncertainty = {p["uncertainty"]};

inline constexpr std::array<PredictedRow, {n_even}> kEvenLeftToCpu{{{{
{rows(p["even_left_to_cpu"])}
}}}};

inline constexpr std::array<PredictedRow, {n_odd}> kOddFreeAllDmaEnabled{{{{
{rows(p["odd_free_all_dma_enabled"])}
}}}};

}}  // namespace meta::amiga::test::slot_tables

#endif  // META_AMIGA_TESTS_SLOT_TABLE_EXPECTATIONS_HPP
"""
    )


def render_all(yaml_text: str) -> dict[Path, str]:
    data = load_yaml(yaml_text)
    digest = hashlib.sha256(yaml_text.encode("utf-8")).hexdigest()
    return {CORE_HEADER: render_core(data, digest), TEST_HEADER: render_expectations(data, digest)}


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the outputs are stale")
    args = parser.parse_args(argv)

    try:
        import yaml  # noqa: F401
    except ImportError:
        print("gen_slot_tables: PyYAML is not installed, skipping", file=sys.stderr)
        return SKIP

    outputs = render_all(YAML_PATH.read_text(encoding="utf-8"))
    stale = []
    for path, text in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if args.check:
            stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        for p in stale:
            print(f"stale: {p} — run scripts/gen_slot_tables.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
