// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 The meta-amiga authors
//
// GENERATED by scripts/gen_slot_tables.py from docs/reference/dma-slot-allocation.yaml.
// Do not edit: change the YAML and regenerate. Transcribed from the Amiga Hardware
// Reference Manual, 3rd edition, and NOT verified against hardware.
// yaml-sha256: ad3fbf41ab1ad0291912317135ab48fa0b0a5a67cd635468d74f6bced2630616
//
// The PREDICTED column of the per-line CPU-slot table (reference section 7). It was worked
// out by hand from the manual, independently of the allocator, so asserting the allocator
// reproduces it checks the mechanism against the paper. No measured column exists.

#ifndef META_AMIGA_TESTS_SLOT_TABLE_EXPECTATIONS_HPP
#define META_AMIGA_TESTS_SLOT_TABLE_EXPECTATIONS_HPP

#include <array>

namespace meta::amiga::test::slot_tables {

enum class Mode { Off, Lores, Hires };

struct PredictedRow {
    Mode mode;
    int planes;
    int value;
};

inline constexpr int kPalClocks = 227;
inline constexpr int kEvenClocksTotal = 114;
inline constexpr int kOddClocksTotal = 113;
inline constexpr int kFixedOddSlots = 27;
inline constexpr int kUncertainty = 1;

inline constexpr std::array<PredictedRow, 11> kEvenLeftToCpu{{
    PredictedRow{Mode::Off, 0, 114},
    PredictedRow{Mode::Lores, 1, 114},
    PredictedRow{Mode::Lores, 2, 114},
    PredictedRow{Mode::Lores, 3, 114},
    PredictedRow{Mode::Lores, 4, 114},
    PredictedRow{Mode::Lores, 5, 94},
    PredictedRow{Mode::Lores, 6, 74},
    PredictedRow{Mode::Hires, 1, 114},
    PredictedRow{Mode::Hires, 2, 114},
    PredictedRow{Mode::Hires, 3, 74},
    PredictedRow{Mode::Hires, 4, 34},
}};

inline constexpr std::array<PredictedRow, 11> kOddFreeAllDmaEnabled{{
    PredictedRow{Mode::Off, 0, 86},
    PredictedRow{Mode::Lores, 1, 66},
    PredictedRow{Mode::Lores, 2, 46},
    PredictedRow{Mode::Lores, 3, 26},
    PredictedRow{Mode::Lores, 4, 6},
    PredictedRow{Mode::Lores, 5, 6},
    PredictedRow{Mode::Lores, 6, 6},
    PredictedRow{Mode::Hires, 1, 46},
    PredictedRow{Mode::Hires, 2, 6},
    PredictedRow{Mode::Hires, 3, 6},
    PredictedRow{Mode::Hires, 4, 6},
}};

}  // namespace meta::amiga::test::slot_tables

#endif  // META_AMIGA_TESTS_SLOT_TABLE_EXPECTATIONS_HPP
